# Generated by Django 6.0.1 on 2026-06-14 09:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=100, verbose_name='اسم السفر')),
                ('chapter_number', models.IntegerField(verbose_name='رقم الأصحاح')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='عنوان الأصحاح (اختياري)')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=250, unique=True, verbose_name='رابط الـ Slug')),
                ('is_active', models.BooleanField(default=False, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'مسابقة',
                'verbose_name_plural': 'المسابقات',
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_value', models.IntegerField(verbose_name='الدرجة')),
                ('time_taken_seconds', models.IntegerField(verbose_name='الوقت المستغرق بالثواني')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ المحاولة')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='quiz.quiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'نتيجة',
                'verbose_name_plural': 'النتائج',
                'ordering': ['-score_value', 'time_taken_seconds'],
            },
        ),
    ]
