# Generated by Django 6.0.1 on 2026-06-14 18:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='تاريخ الإنشاء'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('text', models.TextField(verbose_name='نص السؤال')),
                ('choice_a', models.CharField(max_length=500, verbose_name='الاختيار أ')),
                ('choice_b', models.CharField(max_length=500, verbose_name='الاختيار ب')),
                ('choice_c', models.CharField(blank=True, max_length=500, verbose_name='الاختيار ج')),
                ('choice_d', models.CharField(blank=True, max_length=500, verbose_name='الاختيار د')),
                ('correct_choice', models.CharField(choices=[('a', 'أ'), ('b', 'ب'), ('c', 'ج'), ('d', 'د')], max_length=1, verbose_name='الإجابة الصحيحة')),
                ('explanation', models.TextField(blank=True, verbose_name='التفسير')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quiz.quiz')),
            ],
            options={
                'verbose_name': 'سؤال',
                'verbose_name_plural': 'الأسئلة',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='QuestionResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_choice', models.CharField(choices=[('a', 'أ'), ('b', 'ب'), ('c', 'ج'), ('d', 'د')], max_length=1)),
                ('is_correct', models.BooleanField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='quiz.question')),
                ('score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='quiz.score')),
            ],
            options={
                'verbose_name': 'إجابة',
                'verbose_name_plural': 'الإجابات',
            },
        ),
    ]
