# Generated by Django 6.0.1 on 2026-06-15 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_quiz_created_at_question_questionresponse'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionresponse',
            options={'verbose_name': 'إجابة سؤال', 'verbose_name_plural': 'إجابات الأسئلة'},
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_choice',
            field=models.CharField(choices=[('a', 'أ'), ('b', 'ب'), ('c', 'ج'), ('d', 'د')], default='a', max_length=1, verbose_name='الإجابة الصحيحة'),
        ),
        migrations.AlterField(
            model_name='questionresponse',
            name='is_correct',
            field=models.BooleanField(verbose_name='هل الإجابة صحيحة؟'),
        ),
        migrations.AlterField(
            model_name='questionresponse',
            name='selected_choice',
            field=models.CharField(max_length=1, verbose_name='الاختيار المحدد'),
        ),
    ]
