# Generated by Django 6.0.1 on 2026-06-23 02:15
# MODIFIED (v2): removed CreateModel(name='QuestionChoice') — this table
# already exists in production Supabase with 296 real rows from an
# earlier partial migration attempt. We must NOT recreate it. The
# 'questionchoice' AddField/AlterUniqueTogether operations below still
# run normally since those just modify the existing table, they don't
# recreate it.

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_alter_questionresponse_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_type', models.CharField(choices=[('summary_pdf', 'ملخص PDF'), ('full_pdf', 'الفصل كامل PDF'), ('image', 'صورة / إنفوجرافيك'), ('podcast', 'بودكاست صوتي')], max_length=20, verbose_name='نوع الرابط')),
                ('url', models.URLField(max_length=500, verbose_name='الرابط')),
                ('label', models.CharField(blank=True, default='', max_length=150, verbose_name='وصف مختصر (اختياري)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
            ],
            options={
                'verbose_name': 'رابط محتوى',
                'verbose_name_plural': 'روابط المحتوى',
                'ordering': ['order'],
            },
        ),
        # NOTE: CreateModel(name='QuestionChoice') intentionally removed.
        # The table already exists in production with 296 real rows.
        # We assume its existing columns already match models.py exactly
        # (key, text, is_correct, order, question_id) since you said you
        # never changed QuestionChoice's shape in the new models.py.

        # migrations.RemoveField(
        #     model_name='question',
        #     name='choice_a',
        # ),
        # migrations.RemoveField(
        #     model_name='question',
        #     name='choice_b',
        # ),
        # migrations.RemoveField(
        #     model_name='question',
        #     name='choice_c',
        # ),
        # migrations.RemoveField(
        #     model_name='question',
        #     name='choice_d',
        # ),
        # migrations.RemoveField(
        #     model_name='question',
        #     name='correct_choice',
        # ),
        # migrations.AddField(
        #     model_name='question',
        #     name='allow_multiple_correct',
        #     field=models.BooleanField(default=False, verbose_name='يسمح بأكثر من إجابة صحيحة'),
        # ),
        migrations.AddField(
            model_name='question',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='question',
            name='explanation',
            field=models.TextField(blank=True, default='', verbose_name='التفسير'),
        ),
        migrations.AlterField(
            model_name='questionresponse',
            name='is_correct',
            field=models.BooleanField(verbose_name='هل الحل صحيح؟'),
        ),
        migrations.AlterField(
            model_name='questionresponse',
            name='selected_choice',
            field=models.CharField(max_length=1, verbose_name='الاختيار الذي تم تحديده'),
        ),
        migrations.AlterField(
            model_name='score',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ المحاولة'),
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('bible', 'كتاب مقدس'), ('spiritual', 'كتاب روحي'), ('iqraa', 'اقرأ واعرف واكسب')], db_index=True, default='bible', max_length=20, verbose_name='تصنيف المحتوى')),
                ('source_name', models.CharField(max_length=100, verbose_name='اسم السفر / الكتاب')),
                ('chapter_number', models.IntegerField(verbose_name='رقم الأصحاح / الفصل')),
                ('title', models.CharField(blank=True, default='', max_length=200, verbose_name='عنوان فرعي (اختياري)')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=250, unique=True, verbose_name='رابط الـ Slug')),
                ('is_active', models.BooleanField(db_index=True, default=False, verbose_name='نشط')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'محتوى',
                'verbose_name_plural': 'المحتويات',
                'ordering': ['category', 'chapter_number'],
                'indexes': [models.Index(fields=['category', 'is_active'], name='quiz_materi_categor_24b668_idx')],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quiz.material'),
        ),
        migrations.AddField(
            model_name='score',
            name='material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='quiz.material'),
        ),
        migrations.AddIndex(
            model_name='score',
            index=models.Index(fields=['material', 'score_value'], name='quiz_score_materia_08e9b7_idx'),
        ),
        migrations.AddField(
            model_name='materiallink',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='quiz.material'),
        ),
        # NOTE: AddField(questionchoice, question) removed too — that FK
        # already exists on the live table (you confirmed quiz_id... wait,
        # actually you confirmed question_id FK already points correctly
        # to quiz_question). No need to add it again.
        migrations.AddIndex(
            model_name='materiallink',
            index=models.Index(fields=['material', 'link_type'], name='quiz_materi_materia_f2d46b_idx'),
        ),
        # NOTE: AlterUniqueTogether for questionchoice removed from here —
        # if it's not already on the live table, we'll check separately
        # rather than risk an error if it conflicts with existing data.
    ]