# Generated by Django 6.0.1 on 2026-07-01 12:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_remove_old_quiz_table'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الدرع')),
                ('description', models.TextField(verbose_name='وصف الشرط')),
                ('icon_image_url', models.URLField(blank=True, default='', max_length=500, verbose_name='رابط صورة الدرع')),
                ('condition_type', models.CharField(choices=[('quiz_completion_count', 'عدد مسابقات مكتملة'), ('perfect_score_count', 'عدد مرات الحصول على الدرجة الكاملة'), ('category_completion_count', 'عدد مسابقات مكتملة من تصنيف معين'), ('streak_days', 'أيام متتالية')], max_length=30, verbose_name='نوع الشرط')),
                ('threshold_value', models.PositiveIntegerField(verbose_name='القيمة المطلوبة')),
                ('category_filter', models.CharField(blank=True, choices=[('bible', 'كتاب مقدس'), ('spiritual', 'كتاب روحي'), ('iqraa', 'اقرأ واعرف واكسب')], default='', max_length=20, verbose_name='تصنيف المحتوى (اختياري)')),
                ('is_active', models.BooleanField(default=True, verbose_name='الدرع نشط')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'درع',
                'verbose_name_plural': 'الدروع',
            },
        ),
        migrations.RemoveField(
            model_name='question',
            name='choice_a',
        ),
        migrations.RemoveField(
            model_name='question',
            name='choice_b',
        ),
        migrations.RemoveField(
            model_name='question',
            name='choice_c',
        ),
        migrations.RemoveField(
            model_name='question',
            name='choice_d',
        ),
        migrations.RemoveField(
            model_name='question',
            name='correct_choice',
        ),
        migrations.AddField(
            model_name='question',
            name='allow_multiple_correct',
            field=models.BooleanField(default=False, verbose_name='يسمح بأكثر من إجابة صحيحة'),
        ),
        migrations.CreateModel(
            name='QuestionChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('a', 'أ'), ('b', 'ب'), ('c', 'ج'), ('d', 'د'), ('e', 'هـ'), ('f', 'و'), ('g', 'ز'), ('h', 'ح')], max_length=1, verbose_name='رمز الاختيار')),
                ('text', models.CharField(max_length=500, verbose_name='نص الاختيار')),
                ('is_correct', models.BooleanField(default=False, verbose_name='هل هي الإجابة الصحيحة؟')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='quiz.question')),
            ],
            options={
                'verbose_name': 'اختيار',
                'verbose_name_plural': 'الاختيارات',
                'ordering': ['order'],
                'unique_together': {('question', 'key')},
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_earned', to='quiz.badge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'درع مشترك',
                'verbose_name_plural': 'دروع المشتركين',
                'unique_together': {('user', 'badge')},
            },
        ),
    ]
