"""
Django settings for bible_quiz_project project.

Generated by 'django-admin startproject' using Django 6.0.1.
"""
import os
import environ
import dj_database_url
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# 1. Initialize environ
env = environ.Env(
    DEBUG=(bool, False)
)

# 2. Read the .env file (للتطوير المحلي فقط في حال وجوده)
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

# 3. Update existing Django variables من البيئة السحابية أو المحلية
SECRET_KEY = env('SECRET_KEY', default='django-insecure-j&65=_hgaqqku=^n#f-+ckp&ej6r5v@jrca*vcni_tk@p(als%')
DEBUG = env('DEBUG')

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Custom Application
    'quiz',
]

# Authentication Backends configuration
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]

# Simple redirect rules
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

# Enable unicode characters in URL resolution routing
ALLOW_UNICODE_SLUGS = True

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'bible_quiz_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'bible_quiz_project.wsgi.application'


# Database configuration
# سيبحث تلقائياً عن DATABASE_URL الخاصة بـ Supabase على Vercel، وإذا لم يجدها سيعود للـ SQLite محلياً
# DATABASES = {
#     'default': dj_database_url.config(
#         default=f"sqlite:///{os.path.join(BASE_DIR, 'db.sqlite3')}",
#         conn_max_age=600
#     )
# }
# Database configuration
DATABASE_URL = env('SUPABASE_URL', default=None)

if DATABASE_URL:
    DATABASES = {
        'default': dj_database_url.parse(DATABASE_URL, conn_max_age=600)
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# 4. Supabase variables & Custom configurations
SUPABASE_URL = env('SUPABASE_URL', default='')
SUPABASE_ANON_KEY = env('SUPABASE_ANON_KEY', default='')
SUPABASE_JWT_SECRET = env('SUPABASE_JWT_SECRET', default='')

CLIENT_ID = env('CLIENT_ID', default='')
CLIENT_SECRET = env('CLIENT_SECRET', default='')

# Static files (CSS, JavaScript, Images)
STATIC_URL = 'static/'
